/**
 * Catálogo local de produtos — fallback enquanto a API Spring Boot não estiver disponível.
 * Estrutura alinhada ao contrato esperado da API.
 */
const productCatalog = [
  {
    id: 1,
    name: "Café 100% Arábica",
    category: "Cafés",
    categorySlug: "cafes",
    price: 24.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.5,
    minQuantity: 0.5,
    weightPresets: [1, 1.5, 2, 5],
    image: "../../assets/images/catCafe.png",
    images: ["../../assets/images/catCafe.png"],
    rating: 5,
    reviewCount: 128,
    description:
      "Café 100% arábica selecionado, com aroma intenso e sabor equilibrado. Ideal para preparo filtrado ou espresso.",
    features: [
      "Grãos selecionados",
      "Torra média",
      "Aroma intenso",
      "Ideal para cafeteira e prensa francesa",
    ],
    packaging: "A granel",
    validity: "12 meses",
    storage: "Local seco e arejado",
    referenceWeight: "500g",
  },
  {
    id: 2,
    name: "Café Especial",
    category: "Cafés",
    categorySlug: "cafes",
    price: 32.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.5,
    minQuantity: 0.5,
    weightPresets: [1, 1.5, 2, 5],
    image: "../../assets/images/catGraos.png",
    images: ["../../assets/images/catGraos.png"],
    rating: 5,
    reviewCount: 96,
    description:
      "Blend especial com notas frutadas e corpo aveludado. Produção artesanal com grãos de alta qualidade.",
    features: ["Notas frutadas", "Corpo aveludado", "Produção artesanal"],
    packaging: "A granel",
    validity: "12 meses",
    storage: "Local seco e arejado",
    referenceWeight: "500g",
  },
  {
    id: 3,
    name: "Café Tradicional",
    category: "Cafés",
    categorySlug: "cafes",
    price: 18.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.5,
    minQuantity: 0.5,
    weightPresets: [1, 1.5, 2, 5],
    image: "../../assets/images/catCafe.png",
    images: ["../../assets/images/catCafe.png"],
    rating: 4,
    reviewCount: 74,
    description:
      "Café tradicional de mesa, equilibrado e versátil para o dia a dia.",
    features: ["Sabor equilibrado", "Ideal para o dia a dia"],
    packaging: "A granel",
    validity: "12 meses",
    storage: "Local seco e arejado",
    referenceWeight: "500g",
  },
  {
    id: 4,
    name: "Paçoca Rolha",
    category: "Doces",
    categorySlug: "doces",
    price: 12.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.25,
    minQuantity: 0.25,
    weightPresets: [0.5, 1, 1.5, 2],
    image: "../../assets/images/catDoces.png",
    images: ["../../assets/images/catDoces.png"],
    rating: 5,
    reviewCount: 52,
    description: "Paçoca rolha artesanal, crocante e com sabor tradicional.",
    features: ["Receita tradicional", "Textura crocante"],
    packaging: "A granel",
    validity: "6 meses",
    storage: "Local fresco e seco",
    referenceWeight: "300g",
  },
  {
    id: 5,
    name: "Amendoim Torrado",
    category: "Oleaginosas",
    categorySlug: "oleaginosas",
    price: 9.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.25,
    minQuantity: 0.25,
    weightPresets: [0.5, 1, 1.5, 2],
    image: "../../assets/images/catOleaginosas.png",
    images: ["../../assets/images/catOleaginosas.png"],
    rating: 4,
    reviewCount: 41,
    description: "Amendoim torrado e salgado, crocante e saboroso.",
    features: ["Torrado na hora", "Crocância ideal"],
    packaging: "A granel",
    validity: "4 meses",
    storage: "Local fresco e seco",
    referenceWeight: "500g",
  },
  {
    id: 6,
    name: "Kit Doces Finos",
    category: "Doces",
    categorySlug: "doces",
    price: 42.9,
    soldByWeight: false,
    unit: "unidade",
    increment: 1,
    minQuantity: 1,
    image: "../../assets/images/catFarinhas.png",
    images: ["../../assets/images/catFarinhas.png"],
    rating: 5,
    reviewCount: 33,
    description:
      "Kit com seleção de doces finos artesanais, perfeito para presentear.",
    features: ["Seleção premium", "Embalagem presenteável"],
    packaging: "Caixa",
    validity: "3 meses",
    storage: "Local fresco e seco",
    referenceWeight: "400g",
  },
  {
    id: 7,
    name: "Páprica Doce",
    category: "Temperos",
    categorySlug: "temperos",
    price: 8.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.1,
    minQuantity: 0.1,
    weightPresets: [0.25, 0.5, 1, 2],
    image: "../../assets/images/catTemperos.png",
    images: ["../../assets/images/catTemperos.png"],
    rating: 4,
    reviewCount: 28,
    description: "Páprica doce de alta qualidade para realçar o sabor dos pratos.",
    features: ["Cor vibrante", "Aroma marcante"],
    packaging: "A granel",
    validity: "18 meses",
    storage: "Local seco, ao abrigo da luz",
    referenceWeight: "250g",
  },
  {
    id: 8,
    name: "Mix de Grãos",
    category: "Grãos",
    categorySlug: "graos",
    price: 14.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.5,
    minQuantity: 0.5,
    weightPresets: [1, 1.5, 2, 5],
    image: "../../assets/images/catGraos.png",
    images: ["../../assets/images/catGraos.png"],
    rating: 4,
    reviewCount: 37,
    description: "Mix de grãos selecionados, rico em fibras e nutrientes.",
    features: ["Grãos selecionados", "Rico em fibras"],
    packaging: "A granel",
    validity: "12 meses",
    storage: "Local seco e arejado",
    referenceWeight: "500g",
  },
  {
    id: 9,
    name: "Rapadura Artesanal",
    category: "Doces",
    categorySlug: "doces",
    price: 7.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.25,
    minQuantity: 0.25,
    weightPresets: [0.5, 1, 1.5, 2],
    image: "../../assets/images/catDoces.png",
    images: ["../../assets/images/catDoces.png"],
    rating: 5,
    reviewCount: 45,
    description: "Rapadura artesanal produzida de forma tradicional.",
    features: ["Produção artesanal", "Sabor autêntico"],
    packaging: "A granel",
    validity: "8 meses",
    storage: "Local fresco e seco",
    referenceWeight: "350g",
  },
  {
    id: 10,
    name: "Castanha de Caju",
    category: "Oleaginosas",
    categorySlug: "oleaginosas",
    price: 19.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.25,
    minQuantity: 0.25,
    weightPresets: [0.5, 1, 1.5, 2],
    image: "../../assets/images/catOleaginosas.png",
    images: ["../../assets/images/catOleaginosas.png"],
    rating: 5,
    reviewCount: 61,
    description: "Castanha de caju torrada, crocante e nutritiva.",
    features: ["Fonte de energia", "Textura crocante"],
    packaging: "A granel",
    validity: "6 meses",
    storage: "Local fresco e seco",
    referenceWeight: "300g",
  },
  {
    id: 11,
    name: "Farinha de Mandioca",
    category: "Farinhas",
    categorySlug: "farinhas",
    price: 6.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.5,
    minQuantity: 0.5,
    weightPresets: [1, 1.5, 2, 5],
    image: "../../assets/images/catFarinhas.png",
    images: ["../../assets/images/catFarinhas.png"],
    rating: 4,
    reviewCount: 39,
    description: "Farinha de mandioca fina, ideal para receitas tradicionais.",
    features: ["Textura fina", "Alta qualidade"],
    packaging: "A granel",
    validity: "12 meses",
    storage: "Local seco e arejado",
    referenceWeight: "1kg",
  },
  {
    id: 12,
    name: "Cesta Premium eCafe",
    category: "Cestas",
    categorySlug: "cestas",
    price: 89.9,
    soldByWeight: false,
    unit: "unidade",
    increment: 1,
    minQuantity: 1,
    image: "../../assets/images/catCestas.png",
    images: ["../../assets/images/catCestas.png"],
    rating: 5,
    reviewCount: 22,
    description:
      "Cesta presenteável com seleção premium de produtos eCafe.",
    features: ["Seleção premium", "Ideal para presente"],
    packaging: "Cesta",
    validity: "Variável conforme itens",
    storage: "Consulte rótulos individuais",
    referenceWeight: "1 unidade",
  },
  {
    id: 13,
    name: "Arroz Branco Tipo 1",
    category: "Grãos",
    categorySlug: "graos",
    price: 6.9,
    soldByWeight: true,
    unit: "kg",
    increment: 0.5,
    minQuantity: 0.5,
    weightPresets: [1, 1.5, 2, 5],
    image: "../../assets/images/catGraos.png",
    images: ["../../assets/images/catGraos.png"],
    rating: 5,
    reviewCount: 128,
    description:
      "Arroz branco tipo 1, grãos inteiros e soltinho. Selecionado e de alta qualidade para o dia a dia.",
    features: [
      "Grãos inteiros",
      "Cozimento soltinho",
      "Non-GMO",
      "Sem glúten",
    ],
    packaging: "A granel",
    validity: "12 meses",
    storage: "Local seco e arejado",
    referenceWeight: "1kg",
  },
];

export { productCatalog };
